### ISSUE TITLE
Can we please embrace s-expression instead ?

### ISSUE THREAD

**Issue by Gozala** [RhizomeDB/PomoRA#3]
It may sound like I'm trying to start a preference debate (maybe subconsciously I am ?). However here is my rational for bringing this up

1. Learning this notation adds extra mental overhead. As I read spec I keep coming back to checking what the notation is, which distracts me from actually understanding more important details.
2. To quote WASM rational here "S-expressions are a very old and very simple textual format", it may not be pretty, most don't like it but it's easy to read and understand and all the text editors are able to provide good enough support out of the box.

**Comment by expede** [comment]
PomoRA is not a high level syntax; it's a deep IR pass inside the stack. It's a relational algebra, which have their own syntactic lineage, but this is really just a semantics that is meant to be targeted by the higher levels like PomoLogic and eventual high level syntaxes.

Relational operators are familiar to database folks; despite my personal preference for them, I'm not sure that throwing S-expressions into the mix will be helpful for a large portion of code readers.
